"""Remove relation_type from PaperCompany

Revision ID: 4af27358ad9c
Revises: d1b7f89993c8
Create Date: 2025-12-15 12:02:53.339884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af27358ad9c'
down_revision = 'd1b7f89993c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PaperCompany', schema=None) as batch_op:
        batch_op.drop_column('relation_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PaperCompany', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relation_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
