"""Add AI analysis fields to Paper

Revision ID: 71b6e640691d
Revises: f40c0c0d1404
Create Date: 2025-12-02 10:28:16.153886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b6e640691d'
down_revision = 'f40c0c0d1404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_business_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_academic_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_strengths', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_weaknesses', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Paper', schema=None) as batch_op:
        batch_op.drop_column('ai_status')
        batch_op.drop_column('ai_weaknesses')
        batch_op.drop_column('ai_strengths')
        batch_op.drop_column('ai_summary')
        batch_op.drop_column('ai_academic_score')
        batch_op.drop_column('ai_business_score')

    # ### end Alembic commands ###
