"""add user preferences column

Revision ID: bb93e1d4e68c
Revises: 4af27358ad9c
Create Date: 2025-12-19 10:09:57.589751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb93e1d4e68c'
down_revision = '4af27358ad9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Complaint', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('Paper', schema=None) as batch_op:
        batch_op.alter_column('abstract',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('Review', schema=None) as batch_op:
        batch_op.alter_column('paper_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reviewer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('preferences')

    with op.batch_alter_table('Review', schema=None) as batch_op:
        batch_op.alter_column('reviewer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('paper_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('Paper', schema=None) as batch_op:
        batch_op.alter_column('abstract',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('Complaint', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'General'::character varying"),
               existing_nullable=False)

    # ### end Alembic commands ###
