"""Add interests column to Company

Revision ID: d1b7f89993c8
Revises: c7f3e5d1f4b2
Create Date: 2025-12-09 15:43:02.583000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1b7f89993c8'
down_revision = 'c7f3e5d1f4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.String(length=255), nullable=True))

    with op.batch_alter_table('Complaint', schema=None) as batch_op:
        batch_op.alter_column('paper_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('Paper', schema=None) as batch_op:
        batch_op.alter_column('research_domain',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('ai_business_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('ai_academic_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('ai_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('PaperCompany', schema=None) as batch_op:
        batch_op.alter_column('relation_type',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('Review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('Review_company_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Company', ['company_id'], ['company_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'User', ['reviewer_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('Review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Review_company_id_fkey'), 'Company', ['company_id'], ['company_id'])

    with op.batch_alter_table('PaperCompany', schema=None) as batch_op:
        batch_op.alter_column('relation_type',
               existing_type=sa.String(length=20),
               server_default=sa.text("'facility'::character varying"),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('Paper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ai_status',
               existing_type=sa.String(length=20),
               server_default=sa.text("'Pending'::character varying"),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('ai_academic_score',
               existing_type=sa.Integer(),
               server_default=sa.text('0'),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('ai_business_score',
               existing_type=sa.Integer(),
               server_default=sa.text('0'),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('research_domain',
               existing_type=sa.String(length=120),
               server_default=sa.text("'Unknown'::character varying"),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('Complaint', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'General'::character varying"),
               existing_nullable=False)
        batch_op.alter_column('paper_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('Company', schema=None) as batch_op:
        batch_op.drop_column('interests')

    # ### end Alembic commands ###
