"""add relation_type to PaperCompany

Revision ID: f40c0c0d1404
Revises: fb4133778963
Create Date: 2025-11-29 21:51:15.297337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40c0c0d1404'
down_revision = 'fb4133778963'
branch_labels = None
depends_on = None


def upgrade():
    # 1) kolom toevoegen als nullable
    with op.batch_alter_table('PaperCompany', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('relation_type', sa.String(length=20), nullable=True)
        )

    # 2) bestaande rijen defaulten naar 'facility'
    op.execute('UPDATE "PaperCompany" SET relation_type = \'facility\' WHERE relation_type IS NULL')

    # 3) kolom NOT NULL maken
    with op.batch_alter_table('PaperCompany', schema=None) as batch_op:
        batch_op.alter_column(
            'relation_type',
            existing_type=sa.String(length=20),
            nullable=False
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PaperCompany', schema=None) as batch_op:
        batch_op.drop_column('relation_type')

    # ### end Alembic commands ###
