"""Add file_path to Paper

Revision ID: fb4133778963
Revises: 2cc69d3cddf4
Create Date: 2025-11-22 00:18:57.083693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4133778963'
down_revision = '2cc69d3cddf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=512), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Paper', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
